# Assignment 3 : Logistic Regression

In this assignment you have to use the logistic regression technique you learned in the week 3 of the prescribed course. You have to use numpy to complete the assignment

#### Import the required libraries here

In [21]:
import numpy as np
from sklearn.metrics import confusion_matrix 
from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot as plt
import cv2

##### Define these functions here:
- Sigmoid function: `def sigmoid(x):`

In [3]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

- cost function: `def cost_fn(x,y,theta):` (refer to the course)

In [4]:
def cost_fn(x,y,theta):
    x = np.insert(x,0,1)
    h_theta = sigmoid(np.dot(x,theta))
    

- Gradient descent: `def gradient_descent(X, y, theta, learning_rate=1, iters):`

$\frac{\partial J}{\partial \theta} = \frac{1}{m} \Sigma_{i=1}^m ((h_\theta(x^{(i)})-y^{(i)})x_j^{(i)})$

$\theta_{j+1}^{(i)} = \theta_j^{(i)} - \frac{1}{m} \Sigma_{i=1}^m ((h_\theta(x^{(i)})-y^{(i)})x_j^{(i)})$

Since these are for each element of your matrix. The final expression will be: (if using matrices)
$\theta_{j+1} = \theta_j - \frac{1}{m} \Sigma_{i=1}^m ((h_\theta(x)-y)x_j)$

You have to initialise $\theta$ and update it at each iteration according to this gradient descent equation

In [5]:
def gradient_descent(X, y, theta, iters, learning_rate=1):
    a = learning_rate
    m = X.shape[0]
    x_0 = np.array([[1] for x in range(m)])
    X = np.hstack((x_0, X))
    H_theta = np.empty((m,10), dtype=float)
    for i in range(10): 
        theta_d = theta.copy()
        y_d = y.copy()
        for j in range(m):
            if (y[j] == i):
                y_d[j] = 1
            else:
                y_d[j] = 0
            
        for k in range(iters):
            h_theta = sigmoid(np.dot(X,theta_d))
            theta_d = theta_d - (a/m)*np.dot(X.T, h_theta - y_d)
        
        H_theta[:,i] = h_theta[:,0]
    return H_theta

- Predict: `def predict(X, y, theta, learning_rate=1, iters)`:

In [6]:
def predict(X, y, theta, iters, learning_rate=1):
    
    h_x = gradient_descent(X,y,theta,iters,learning_rate)
    
    prediction = np.argmax(h_x, axis = 1).reshape(X.shape[0],1)
    
    return prediction

### Load MNSIT data here

There are two file, X.csv and y.csv.
You have to load these csv files (read about csv in python) and store them in python variables. 
There are 5000 images, each line in X.csv is an image (pixels of image of size 20x20 are concatenated to size 400x1) and each line is y.csv is the label of that image (label in n-th line in y.csv corresponds to image in n-th line in X.csv)

In [12]:
X = np.loadtxt("X.csv", delimiter = ",")
y = np.loadtxt("y.csv")
m = y.shape[0]
n = X.shape[0]
y_input = y.reshape(m,1)
theta = np.ones([401,1])
print(theta.shape)

(401, 1)


Now your task is to:
1. Reshape these to 20x20 and show any 5 of them (random) here. 
2. For regression, you have to use the 400x1 data only. (X will be a 5000x400 matrix and y will be a 1x400 matrix)
3. Get you prediction and compare it with the labels in y
4. Calculate the error %

In [ ]:
# Reshaping and displaying images corresponding to 5 (random) rows of X
random_indices = np.random.choice(X.shape[0], size = 5, replace = False)
random_rows = X[random_indices, :]
for i in range(5):
    cv2.imshow(f"Image {i}", random_rows[i].reshape(20,20))
cv2.waitKey(0)
cv2.destroyAllWindows()

# Regression
prediction = predict(X, y_input, theta, 1000, 0.1)
print(prediction)

error = 0
for i in range(m):
    if prediction[i]!=y[i]:
        error += 1
error_percentage = (error/m)*100
print(error_percentage)

Generate the [confusion matrix](https://en.wikipedia.org/wiki/Confusion_matrix) here and show it here: 


In [19]:
conf_matrix = np.zeros([10,10], dtype = int)
for i in range(10):
    for j in range(m):
        if (y[j] == i):
            conf_matrix[prediction[j],i] += 1
print(conf_matrix)
                

[[483   0  11   1   1  10   5   7   2   5]
 [  0 480   9   4   3   7   3   7   4   4]
 [  1   4 425  17   6   5   5   7   9   3]
 [  1   1   6 425   0  36   0   0  16   8]
 [  0   0  12   0 447  13   4   8   2   9]
 [  0   4   1  24   1 383   6   0  11   6]
 [  8   1   5   3   8   9 467   2   2   1]
 [  1   2   7   7   1   0   3 450   0  24]
 [  5   8  20  10   5  24   5   0 445   4]
 [  1   0   4   9  28  13   2  19   9 436]]


#### Bonus task: 
Use [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) to perform logistic regression (just a single function which will handle all your task :P)

In [ ]:
logRegr = LogisticRegression(solver='liblinear')
logRegr.fit(X,y) 
predictions = logRegr.predict(X) 
cm = confusion_matrix(predictions,y) 
print(cm)
print("Error % =", logRegr.score(X,y))